<a href="https://colab.research.google.com/github/denzilseason/Linear-Algebra-58019/blob/main/Final_Exam.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##Problem 1. Student A, Student B, and Student C have a total of Php 89 cash in their banks. Student A has 6 less than Student C. Student B has 3 times what Student C has. How much does each student have? (30 points)

In [13]:
import numpy as np
A = np.array([[1,1,1],[1,0,4],[0,0,5]]) #First equation
B = np.array([[89],[89],[95]]) #Second equation
X = np.linalg.inv(A).dot(B) #Amount each student have
print(X)


[[13.]
 [57.]
 [19.]]


##Problem 2. Solve each system:
3x - y + z = 5
9x - 3y +3z = 15
-12x + 4y -4z = -20

In [11]:
import numpy as np
from scipy.linalg import solve
A=np.array([[3,-1,1],[9,-3,3],[-12,4,-4]])
print(A)
B=np.array([[5],[15],[-20]])
print(B)
X=solve(A,B)
print(X) #Problem is not answerable because matrix is singular, so codes show error. 0 determinant does not have an inverse.

[[  3  -1   1]
 [  9  -3   3]
 [-12   4  -4]]
[[  5]
 [ 15]
 [-20]]


LinAlgError: ignored

##Problem 3.

In [15]:
import numpy as np
from scipy.linalg import solve
#from numpy.linalg import eig

A = np.array([[8,5,-6],[-12,-9,12],[-3,-3,5]])
print(A)

a,b = np.linalg.eig(A)
print("The eigenvalues is/are:",a)
print("The right eigenvectors are:",b)

#x = v.round()
#print(x)

[[  8   5  -6]
 [-12  -9  12]
 [ -3  -3   5]]
The eigenvalues is/are: [-1.  3.  2.]
The right eigenvectors are: [[ 3.01511345e-01 -7.07106781e-01  7.07106781e-01]
 [-9.04534034e-01  7.07106781e-01  1.53837015e-15]
 [-3.01511345e-01 -2.26120075e-15  7.07106781e-01]]
