<a href="https://colab.research.google.com/github/denzilseason/Linear-Algebra-58019/blob/main/Midterm_Exam.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Midterm Exam

##Question 1. Create a Python code that displays a square matrix whose length is 5 (10 points)

In [10]:
import numpy as np
A=np.zeros((5,5)) #To create a square matrix with length of 5
print(A)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


##Question 2. Create a Python code that displays a square matrix whose elements below the principal diagonal are zero (10 points)

In [11]:
import numpy as np
A = np.identity(5)   #To create square matrix
print(A)             #To display a square matrix with zero elements below the principal diagonal

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


##Question 3. Create a Python code that displays a square matrix which is symmetrical (10 points)

In [13]:
import numpy as np
A = np.array([[2,1,4],[1,5,7],[4,7,6]]) #To create symmetrical square matrix
print(A)

[[2 1 4]
 [1 5 7]
 [4 7 6]]


##Question 4. What is the inverse of matrix C? Show your solution by python coding. (20 points)

In [5]:
import numpy as np
C=np.array([[1,2,3],[2,3,3],[3,4,-2]]) #To declare the values of matrix
print(C)
invC=(np.linalg.inv(C))
print(invC)                            #To show the inverse of Matrix C

[[ 1  2  3]
 [ 2  3  3]
 [ 3  4 -2]]
[[-3.6  3.2 -0.6]
 [ 2.6 -2.2  0.6]
 [-0.2  0.4 -0.2]]


##Question 5. What is the determinant of the given matrix in Question 4? Show your solution by python coding. (20 points)

In [15]:
import numpy as np
A =np.array([[1,2,3],[2,3,3],[3,4,-2]]) #Declare the values of matrix.
print(A)
print(np.linalg.det(A)) #To display the determinant of A
print(round(np.linalg.det(A))) #To display the rounded determinant of A

[[ 1  2  3]
 [ 2  3  3]
 [ 3  4 -2]]
5.000000000000001
5


##Question 6. Find the roots of the linear equations by showing its python codes (30 points)

5X1 + 4X2 + X3 = 3.4

10X1 + 9X2 + 4X3 = 8.8

10X1 + 13X2 + 15X3 = 19.2

In [14]:
import numpy as np
A = np.array([[5,4,1],[10,9,4],[10,13,15]])
B = np.array([[3.4],[8.8],[19.2]])
roots = np.linalg.inv(A).dot(B)
print(roots)


[[0.2]
 [0.4]
 [0.8]]
