<a href="https://colab.research.google.com/github/denzilseason/Linear-Algebra-58019/blob/main/Practical_Lab_Exam_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Practical Lab Exam 1

##Problem 1

###Problem 1 A.

In [4]:
import numpy as np
A = np.array([[1,2,3],[4,5,6]])
B = np.array([[1,2],[3,4],[5,6]])

product = np.dot(A,B)
print(product)

[[22 28]
 [49 64]]


###Problem 1 B.

In [5]:
import numpy as np
D = np.array ([[1,2],[3,4]])
print (D+D)

[[2 4]
 [6 8]]


###Problem 1 C.

In [6]:
import numpy as np
C = np.array([[1,2,3],[4,5,6],[7,8,9]])
S = 2*C
print(S)

[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]


##Problem 2

In [18]:
import numpy as np
Θ = np.array([5,3,-1])
print(Θ)
print(Θ.shape)
print(Θ.size)
print(Θ.ndim)

[ 5  3 -1]
(3,)
3
1
