<a href="https://colab.research.google.com/github/denzilseason/Linear-Algebra-58019/blob/main/Python_Exercise_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
##Python Program to inverse a 4x4 matrix A = ([6,1,1,3],[4,-2,5,1],[2,8,7,6],[3,1,9,7])
import numpy as np
A=np.array([[1,2],[4,7]])
print(A)
invA=(np.linalg.inv(A))
print(invA)

##Python Program to transpose a 4x4 matrix A = ([6,1,1,3],[4,-2,5,1],[2,8,7,6],[3,1,9,7])
B=np.transpose(A)
print(B)

##Program code product of A and InvA
prod=np.dot(A,invA)
print(prod)

[[1 2]
 [4 7]]
[[-7.  2.]
 [ 4. -1.]]
[[1 4]
 [2 7]]
[[1. 0.]
 [0. 1.]]
