<a href="https://colab.research.google.com/github/denzilseason/Linear-Algebra-58019/blob/main/Python_Exercise_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##Representing  Vectors

In [2]:
import numpy as np
A = np.array([4,3])
B = np.array([2,5])

print('Vector A is',A)
print('Vector B is',B)

Vector A is [4 3]
Vector B is [2 5]


##Describing Vectors in Numpy

In [6]:
import numpy as np
ball1 = np.array([1,2,3])
ball2 = np.array([0,1,-1])
pool = np.array([ball1,ball2])
pool.shape
pool.ndim

2

In [13]:
U = np.array([[1,2,3],[4,5,6]])
U.size

6

#Spaces

##Vector spaces are mathematical objects that abstractly capture the geometry and algebra of linear equations.

###Addition of Vectors

In [14]:
addend1 = np.array([0,0,0])
addend2 = np.array([1,1,0])
sum = addend1 + addend2
print(sum)

[1 1 0]


In [18]:
addend1 = np.array([0,0,0])
addend2 = np.array([1,1,0])
resultant = np.add(addend1,addend2)
print(resultant)

[1 1 0]


#Subtraction of Vector

##Subtract the compononents of addend2 from addend1

In [19]:
addend1 = np.array([0,0,0])
addend2 = np.array([1,1,0])
difference = addend1 - addend2
print(difference)

[-1 -1  0]


In [20]:
difference2 = np.subtract(addend1,addend2)
print(difference2)

[-1 -1  0]


#Scaling

In [21]:
A = np.array([1,5,8,9])
S = 5*A
print(S)

[ 5 25 40 45]


In [26]:
import numpy as np
A = np.array([2,3])
B= np.array([1,7])

output = np.cross(A,B)       #Cross product of A and B
print(output)

11


In [25]:
import numpy as np
A = np.array([2,3])
B = np.array([1,7])

output = np.dot(A,B)        #Dot Product of A and B
print(output)

23
