<a href="https://colab.research.google.com/github/denzilseason/Linear-Algebra-58019/blob/main/Python%20Exercise%201.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Matrix and its Operations

In [2]:
#numpy
import numpy as np
A = np.array ([[-5,4],[0,1]])
B = np.array ([[6,2],[-3,3]]) #This is an example of Addition of Matrices
print (a+b)

[[ 1  6]
 [-3  4]]


In [4]:
#numpy
import numpy as np
A = np.array ([[-5,4],[0,1]])
B = np.array ([[6,2],[-3,3]]) #This is an example of Addition of Matrices B-A
print (b-a)

[[11 -2]
 [-3  2]]


In [3]:
#numpy
import numpy as np
A = np.array ([[-5,4],[0,1]])
B = np.array ([[6,2],[-3,3]]) #This is an example of Subraction of Matrices A-B
print (a-b)

[[-11   2]
 [  3  -2]]
