<a href="https://colab.research.google.com/github/denzilseason/Linear-Algebra-58019/blob/main/Linear_Transformation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##To find the inverse of a matrix, the matrix is passed to the linarlg.inv() of the Numpy module:

In [11]:
import numpy as np
A=np.array([[4,3,2],[-2,2,3],[3,-5,2]])  #creation of matrix A
print(A)
inv_A=np.linalg.inv(A)
print(inv_A)

[[ 4  3  2]
 [-2  2  3]
 [ 3 -5  2]]
[[ 0.15447154 -0.1300813   0.04065041]
 [ 0.10569106  0.01626016 -0.1300813 ]
 [ 0.03252033  0.23577236  0.11382114]]


In [15]:
B=np.array([[25],[-10],[-4]])
print(B)

[[ 25]
 [-10]
 [ -4]]


In [16]:
X=np.dot(inv_A,B)
print(X)

[[ 5.]
 [ 3.]
 [-2.]]
