<a href="https://colab.research.google.com/github/denzilseason/Linear-Algebra-58019/blob/main/Vectors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Matrix Algebra

In [1]:
#numpy
import numpy as np
a = np.array([1,2,3]) #This is an example of1x3 matrix
print (a)


[1 2 3]


In [2]:
import numpy as np
b = np.array ([[1,2,3],[4,5,6]]) #This is an example of 2x3 matrix
print (b)

[[1 2 3]
 [4 5 6]]


In [3]:
import numpy as np
c = np.array ([[1,2,3],[4,5,6],[7,8,9]]) #This is an example of 3x3 matrix
print (c)


[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [4]:
import numpy as np
d= np.full ((3,3),7)
print (d)


[[7 7 7]
 [7 7 7]
 [7 7 7]]


In [5]:
import numpy as np
e = np.diagonal ([[1,2,3],[4,5,6],[7,8,9]])
print (e)


[1 5 9]


In [6]:
import numpy as np
f =np.eye (3)
print (f)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [7]:
import numpy as np
g = np.zeros ((2,2))
print (g)

[[0. 0.]
 [0. 0.]]


In [9]:
import numpy as np
h = np.empty ((0,13))
print (h)

[]


In [10]:
import numpy as np
d= np.full ((3,3),7)
print (d+d)

[[14 14 14]
 [14 14 14]
 [14 14 14]]


In [11]:
import numpy as np
d= np.full ((3,3),7)
print (d-d)

[[0 0 0]
 [0 0 0]
 [0 0 0]]
